// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bids.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids ("product_id", "user_id", "amount_cents")
VALUES ($1, $2, $3)
RETURNING id, product_id, user_id, amount_cents, created_at, updated_at
`

type CreateBidParams struct {
	ProductID   uuid.UUID `json:"product_id"`
	UserID      uuid.UUID `json:"user_id"`
	AmountCents int64     `json:"amount_cents"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.ProductID, arg.UserID, arg.AmountCents)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.AmountCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBidsByProductID = `-- name: GetBidsByProductID :many
SELECT id, product_id, user_id, amount_cents, created_at, updated_at
FROM bids
WHERE product_id = $1
ORDER BY amount_cents DESC
`

func (q *Queries) GetBidsByProductID(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByProductID = `-- name: GetHighestBidByProductID :one
SELECT id, product_id, user_id, amount_cents, created_at, updated_at
FROM bids
WHERE product_id = $1
ORDER BY amount_cents DESC
`

func (q *Queries) GetHighestBidByProductID(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByProductID, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.AmountCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
