// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prodocts.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
        "seller_id",
        "name",
        "description",
        "base_price_cents",
        "auction_end"
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateProductParams struct {
	SellerID       uuid.UUID `json:"seller_id"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	BasePriceCents int64     `json:"base_price_cents"`
	AuctionEnd     time.Time `json:"auction_end"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SellerID,
		arg.Name,
		arg.Description,
		arg.BasePriceCents,
		arg.AuctionEnd,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, seller_id, name, description, base_price_cents, auction_end, is_sold, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.Name,
		&i.Description,
		&i.BasePriceCents,
		&i.AuctionEnd,
		&i.IsSold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
